"""Symmetry and combinatorial classification of ray paths: the authority for
the crystal point groups, the fold group ``G`` and the ``Phi`` classes.

This subpackage is pure numpy and never imports JAX.  It depends on
:mod:`lumice_integral.geometry` (face normals, optical gates, the wedge-angle
kernel) and never the other way round (checked statically by
``tests/test_symmetry_dependency_direction.py``).

Migrated from the writing repository's ``halo_notes.math`` (2026-09-24,
task-symmetry-authority); public names are kept 1:1, so downstream code
migrates by rewriting ``halo_notes.math`` to ``lumice_integral.symmetry``:

- ``group``: ``D6`` as permutations of the face numbers (ch1 table 1.7 order),
  applied band by band to pyramid faces.
- ``reflection_group``: the 12-element fold group ``G`` generated by the
  prism's mirrors (ch3 numbers #1-#12), its conjugacy / eigenvalue classes,
  commutation with ``R_z(theta)``, ray-path matrices and the Lumice ``PBD``
  orbit of a face sequence.
- ``signature``: the 24-element ``D6H`` table -- the only ``D6h`` element
  table in this repository (:func:`lumice_integral.path_class.hexprism_symmetry_matrices`
  returns it) -- the canonical signature ``(M, n_a, M^-1 n_b)`` and the ``Phi``
  classes (34 = 6 + 12 + 16 on the prism).
- ``ground_truth``: parser of the packaged ch3 ground-truth list
  (``data/raypath_ground_truth.txt``).
- ``attitude``: column attitude ``R_z(psi) R_y(90) R_z(theta)`` and the sky
  direction ``R M R^T s_hat`` (the writing series' ``sun_vector`` is
  :func:`lumice_integral.camera.sun_direction` here).

The submodules are not flattened into one namespace: ``group`` and
``reflection_group`` each define their own ``Element`` (``D6`` permutations
versus elements of ``G``), so names are reached through their module.
"""

from . import attitude, ground_truth, group, reflection_group, signature

__all__ = ["attitude", "ground_truth", "group", "reflection_group", "signature"]
