"""Single-pixel component discovery: synthetic unit checks and strip-pixel regressions.

The pixel regressions are the pixels of ``explore-component-discovery``
(``exp03_pixel_grid_results.csv`` and experiments #5–#7).  Their candidates
come from one module-level production store (:data:`STORE_N` points, the
default 0.2 deg band; task ``phase1-seeds-from-store``, which replaced the
400k-sample Haar prescan of the survey): the component counts and kinds are
the survey's, the funnel counts (``pool_count``/``raw_cluster_count``/
``admissible_count``) are this store's.  The arclengths were regenerated by
this module's implementation (task-continuation-gates-and-fixtures halved
the survey's second-traversal values; task-pixel-pipeline-v2 left them
unchanged); the store moved the long loops by less than ``ARCLENGTH_RTOL``
and the two short caustic loops (0.19 / 0.17 rad) by 9e-4 relative, the
seed-position dependence of a short loop's polyline length (their pins are
the store's values).
"""

from __future__ import annotations

import dataclasses
from types import SimpleNamespace

import jax.numpy as jnp
import numpy as np
import pytest

import lumice_integral.discovery as discovery_module
from lumice_integral.analytic import BODY_AXIS, direction_map, tangent_basis
from lumice_integral.camera import linear_pixel_outgoing_direction
from lumice_integral.canonical_scene import (
    CANONICAL_REFRACTIVE_INDEX,
    CANONICAL_RENDER,
    canonical_crystal,
    canonical_incident_direction,
    canonical_pixel_problem,
    canonical_sun_direction,
    canonical_target_direction,
)
from lumice_integral.continuation import (
    ContinuationOptions,
    DomainEvaluation,
    EventCandidate,
    FiberProblem,
    FiberStatus,
    TargetChart,
    TerminationReason,
    trace_fiber,
)
from lumice_integral.discovery import (
    ARC_EVENTS,
    DISCOVERY_EVENT_NAMES,
    ComponentDiscoveryResult,
    DiscoveredComponent,
    IncompleteCandidate,
    _geodesic_cluster,
    _trace_and_classify,
    check_band_coverage,
    discover_components,
    distance_to_curve,
    miss_probability,
    retarget_problem,
)
from lumice_integral.optics import path_domain
from lumice_integral.resample import OpenArc
from lumice_integral.s2_store import StoreSeeds, build_event_store
from lumice_integral.so3 import exp
from lumice_integral.weights import WeightEvaluator

STORE_N = 1_000_000
DISCOVERY_KWARGS = dict(
    band_half_width_deg=0.2,
    cluster_radius_rad=0.3,
)
ARCLENGTH_RTOL = 1e-3


def _store(members, n: int = STORE_N, refractive_index: float = CANONICAL_REFRACTIVE_INDEX):
    return build_event_store(canonical_crystal(), refractive_index, members, n, run_checks=False)


# The production store of 3-5 on the canonical crystal as one shared seed source; the kept-event count is
# pinned so a sampling change cannot hide behind unchanged component counts.
STORE = _store([(3, 5)])
SEEDS = StoreSeeds(STORE, (3, 5), canonical_sun_direction())

# Regenerated baselines (this implementation, default parameters).  The survey
# recorded 4.758247 / 6.2437 / 3.1302 for the same pixels: second-traversal
# lengths of loops shorter than pi under the absolute closure gate retired by
# task-continuation-gates-and-fixtures (rows 150/151/225 exactly halved; row
# 226, longer than pi, is unchanged).
CANONICAL_ARCLENGTH = 2.379121
ROW_225_ARCLENGTH = 3.121867
ROW_226_ARCLENGTH = 3.130201
ROW_151_ARCLENGTH = 2.391079


def pixel_target(row: int, column: int) -> np.ndarray:
    return linear_pixel_outgoing_direction(row, column, **CANONICAL_RENDER)


def discover_pixel(row: int, column: int, **kwargs) -> ComponentDiscoveryResult:
    return discover_components(
        pixel_target(row, column), SEEDS, **DISCOVERY_KWARGS, **kwargs
    )


def test_seed_store_is_the_production_store_of_the_canonical_scene() -> None:
    assert SEEDS.n == STORE_N and len(STORE.events) == 160216
    assert SEEDS.refractive_index == CANONICAL_REFRACTIVE_INDEX
    assert np.array_equal(SEEDS.incident_direction, canonical_incident_direction())
    assert SEEDS.crystal.a == canonical_crystal().a and SEEDS.crystal.h == canonical_crystal().h


def _closed_record(arclength: float, poses: int) -> DiscoveredComponent:
    return DiscoveredComponent(
        seed=np.eye(3),
        kind="closed",
        result=SimpleNamespace(poses=np.zeros((poses, 3, 3))),
        arclength=arclength,
        status=FiberStatus.CLOSED,
        reason=TerminationReason.CLOSED_LOOP,
    )


def _incomplete_record(reason: TerminationReason = TerminationReason.STEP_BUDGET) -> IncompleteCandidate:
    return IncompleteCandidate(
        seed=np.eye(3),
        result=SimpleNamespace(poses=np.zeros((251, 3, 3))),
        status=FiberStatus.BUDGET_EXHAUSTED,
        reason=reason,
        cause="incomplete_not_converged",
    )


# --- types and synthetic helpers -----------------------------------------------


def test_result_types_are_frozen_and_count_properties_match_tuples() -> None:
    result = ComponentDiscoveryResult(
        components=(_closed_record(1.0, 10),),
        incomplete=(_incomplete_record(),),
        completeness="unknown",
        pool_count=3,
        extra_seed_count=0,
        raw_cluster_count=2,
        admissible_count=2,
        events={name: 0 for name in DISCOVERY_EVENT_NAMES},
        trace_seconds=0.0,
    )
    assert result.component_count == 1
    assert result.arc_count == 0
    assert result.incomplete_count == 1
    assert result.components[0].start_reason is None
    with pytest.raises(dataclasses.FrozenInstanceError):
        result.completeness = "complete"  # type: ignore[misc]
    with pytest.raises(dataclasses.FrozenInstanceError):
        result.components[0].arclength = 2.0  # type: ignore[misc]


def test_arc_events_are_exactly_the_five_named_boundaries() -> None:
    assert ARC_EVENTS == {
        TerminationReason.TIR_BOUNDARY,
        TerminationReason.BRANCH_BOUNDARY,
        TerminationReason.PATH_INFEASIBLE,
        TerminationReason.VISIBILITY_BOUNDARY,
        TerminationReason.CHART_BOUNDARY,
    }
    assert TerminationReason.RANK_LOSS not in ARC_EVENTS
    assert TerminationReason.STEP_BUDGET not in ARC_EVENTS


def test_geodesic_cluster_separates_two_tight_clusters() -> None:
    rng = np.random.default_rng(0)
    centres = [np.array([1.0, 0.2, -0.3]), np.array([-0.5, 1.4, 0.8])]
    rotations = []
    for centre in centres:
        for _ in range(5):
            rotations.append(np.asarray(exp(jnp.asarray(centre + 0.01 * rng.standard_normal(3)))))
    rotations = np.stack(rotations)
    clusters = _geodesic_cluster(rotations, radius=0.3)
    assert sorted(sorted(c) for c in clusters) == [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


def test_geodesic_cluster_of_empty_pool_is_empty() -> None:
    assert _geodesic_cluster(np.zeros((0, 3, 3)), radius=0.3) == []


def test_distance_to_curve_is_the_minimum_over_the_sampled_poses() -> None:
    axis = np.array([0.0, 0.0, 1.0])
    poses = np.stack([np.asarray(exp(jnp.asarray(theta * axis))) for theta in np.linspace(0.0, 1.0, 11)])
    on_curve = np.asarray(exp(jnp.asarray(0.55 * axis)))  # halfway between two samples 0.1 apart
    assert distance_to_curve(on_curve, poses) == pytest.approx(0.05, abs=1e-12)
    off_curve = poses[5] @ np.asarray(exp(jnp.asarray(np.array([0.3, 0.0, 0.0]))))  # 0.3 off sample 5
    assert distance_to_curve(off_curve, poses) == pytest.approx(0.3, abs=1e-9)
    assert distance_to_curve(poses[3], poses) == pytest.approx(0.0, abs=1e-12)


# --- the closed / arc / incomplete branches on an analytic two-sided arc ----------


def _constant(value: float) -> WeightEvaluator:
    return WeightEvaluator(lambda _: value, "dimensionless", "test constant")


def _circle_angle(rotation) -> float:
    rotation = np.asarray(rotation)
    return float(np.arctan2(rotation[1, 0], rotation[0, 0]))


def _capped_circle(
    theta_min: float | None,
    theta_max: float | None,
    *,
    hi_kind: TerminationReason = TerminationReason.VISIBILITY_BOUNDARY,
    lo_kind: TerminationReason = TerminationReason.TIR_BOUNDARY,
) -> FiberProblem:
    """The analytic body-axis circle, cut at ``theta_min``/``theta_max`` (``None`` = uncut)."""

    def domain(rotation):
        theta = _circle_angle(rotation)
        margins = {}
        if theta_max is not None:
            margins["cap_hi"] = theta_max - theta
        if theta_min is not None:
            margins["cap_lo"] = theta - theta_min
        if theta_max is not None and margins["cap_hi"] < 0.0:
            return DomainEvaluation(False, margins, EventCandidate(hi_kind, margins["cap_hi"]))
        if theta_min is not None and margins["cap_lo"] < 0.0:
            return DomainEvaluation(False, margins, EventCandidate(lo_kind, margins["cap_lo"]))
        return DomainEvaluation(True, margins)

    return FiberProblem(
        path="analytic-body-axis",
        incident_direction=jnp.array([1.0, 0.0, 0.0], dtype=jnp.float64),
        target_chart=TargetChart(BODY_AXIS, tangent_basis(BODY_AXIS)),
        direction_evaluator=direction_map,
        seed=jnp.eye(3, dtype=jnp.float64),
        domain_and_event_evaluator=domain,
        weight_evaluators={"rho_pose": _constant(1.0)},
    )


def _classify(problem: FiberProblem, options: ContinuationOptions | None = None):
    from collections import Counter

    events: Counter = Counter()
    timings: Counter = Counter()
    record = _trace_and_classify(problem, options or ContinuationOptions(), np.eye(3), events, timings)
    return record, events, timings


def test_two_named_events_stitch_into_an_arc_component() -> None:
    record, events, timings = _classify(_capped_circle(-1.3, 2.0))
    assert isinstance(record, DiscoveredComponent) and record.kind == "arc"
    assert events["arc_stitched"] == 1 and timings["trace_s"] > 0.0
    arc = record.result
    assert isinstance(arc, OpenArc)
    assert record.status == FiberStatus.EVENT_TERMINATED
    assert record.reason == TerminationReason.VISIBILITY_BOUNDARY
    assert record.start_reason == TerminationReason.TIR_BOUNDARY
    assert arc.forward.reason == TerminationReason.VISIBILITY_BOUNDARY
    assert arc.backward.reason == TerminationReason.TIR_BOUNDARY
    # White-box: the stitched arrays run monotonically from the backward end
    # through the seed to the forward end, every tangent points along +theta,
    # and the increments are the chords between consecutive poses.
    thetas = np.array([_circle_angle(pose) for pose in arc.poses])
    assert np.all(np.diff(thetas) > 0.0)
    assert -1.3 <= thetas[0] < 0.0 < thetas[-1] <= 2.0
    assert np.allclose(arc.poses[arc.seed_index], np.eye(3), atol=1e-12)
    assert np.all(arc.tangents @ np.array([0.0, 0.0, 1.0]) > 0.99)
    assert np.allclose(arc.arclength_increments, np.diff(thetas), atol=1e-10)
    assert record.arclength == pytest.approx(thetas[-1] - thetas[0], abs=1e-10)
    assert len(arc.branch_diagnostics.accepted_margins) == len(arc.poses)
    assert len(arc.poses) == len(arc.forward.poses) + len(arc.backward.poses) - 1


def test_closed_loop_is_a_closed_component_without_a_backward_trace() -> None:
    record, events, _ = _classify(_capped_circle(None, None))
    assert isinstance(record, DiscoveredComponent) and record.kind == "closed"
    assert record.status == FiberStatus.CLOSED and record.start_reason is None
    assert record.arclength == pytest.approx(2.0 * np.pi, rel=1e-6)
    assert not any(events.values())


def test_backward_trace_that_does_not_end_on_a_named_event_leaves_the_candidate_incomplete() -> None:
    # Cut on the forward side only: the backward trace runs until its
    # arclength budget (no event) -> incomplete, both traces kept.
    options = ContinuationOptions(maximum_arclength=1.0)
    record, events, _ = _classify(_capped_circle(None, 0.5), options)
    assert isinstance(record, IncompleteCandidate)
    assert record.cause == "arc_backward_failed" and events["arc_backward_failed"] == 1
    assert record.reason == TerminationReason.VISIBILITY_BOUNDARY
    assert record.backward is not None
    assert record.backward.status == FiberStatus.BUDGET_EXHAUSTED
    assert record.backward.reason == TerminationReason.ARCLENGTH_BUDGET


def test_unnamed_event_is_incomplete_and_not_traced_backward(monkeypatch) -> None:
    calls = []
    real_trace = trace_fiber

    def counting_trace(problem, options=None, *args, **kwargs):
        calls.append(options.initial_tangent_sign if options is not None else 1)
        return real_trace(problem, options, *args, **kwargs)

    monkeypatch.setattr(discovery_module, "trace_fiber", counting_trace)
    record, events, _ = _classify(_capped_circle(None, 0.5, hi_kind=TerminationReason.RANK_LOSS))
    assert isinstance(record, IncompleteCandidate)
    assert record.cause == "incomplete_unnamed_event" and events["incomplete_unnamed_event"] == 1
    assert record.reason == TerminationReason.RANK_LOSS and record.backward is None
    assert calls == [1]


def test_backward_trace_that_closes_is_an_anomaly_not_a_component(monkeypatch) -> None:
    forward = trace_fiber(_capped_circle(None, 0.5))
    closed = trace_fiber(_capped_circle(None, None))
    assert forward.reason == TerminationReason.VISIBILITY_BOUNDARY and closed.status == FiberStatus.CLOSED

    def fake_trace(problem, options=None, *args, **kwargs):
        return closed if options is not None and options.initial_tangent_sign == -1 else forward

    monkeypatch.setattr(discovery_module, "trace_fiber", fake_trace)
    record, events, _ = _classify(_capped_circle(None, 0.5))
    assert isinstance(record, IncompleteCandidate)
    assert record.cause == "arc_backward_closed_anomaly" and events["arc_backward_closed_anomaly"] == 1
    assert record.backward is closed and record.result is forward


def test_budget_exhausted_forward_trace_is_incomplete_not_converged() -> None:
    record, events, _ = _classify(_capped_circle(None, None), ContinuationOptions(maximum_accepted_steps=5))
    assert isinstance(record, IncompleteCandidate)
    assert record.cause == "incomplete_not_converged" and events["incomplete_not_converged"] == 1
    assert record.status == FiberStatus.BUDGET_EXHAUSTED and record.backward is None


def test_a_reversed_caller_orientation_still_traces_the_other_way_for_the_arc() -> None:
    record, _, _ = _classify(_capped_circle(-1.3, 2.0), ContinuationOptions(initial_tangent_sign=-1))
    assert isinstance(record, DiscoveredComponent) and record.kind == "arc"
    assert record.reason == TerminationReason.TIR_BOUNDARY
    assert record.start_reason == TerminationReason.VISIBILITY_BOUNDARY
    assert record.arclength == pytest.approx(3.3, abs=0.15)


# --- pixel regressions -------------------------------------------------------------


@pytest.fixture(scope="module")
def canonical_discovery() -> ComponentDiscoveryResult:
    return discover_pixel(150, 150)


@pytest.fixture(scope="module")
def row_225_discovery() -> ComponentDiscoveryResult:
    return discover_pixel(225, 150)


@pytest.fixture(scope="module")
def row_226_discovery() -> ComponentDiscoveryResult:
    return discover_pixel(226, 150)


def test_canonical_pixel_has_one_closed_component(canonical_discovery: ComponentDiscoveryResult) -> None:
    result = canonical_discovery
    assert result.completeness == "complete"
    assert result.pool_count == 5024 and result.extra_seed_count == 0
    assert result.raw_cluster_count == 6 and result.admissible_count == 6
    assert result.component_count == 1 and result.arc_count == 0
    assert result.incomplete_count == 0
    # Six admissible candidates on one loop: one trace, five folded by distance.
    assert result.events == {**{name: 0 for name in DISCOVERY_EVENT_NAMES}, "dedup_merged": 5}
    assert result.trace_seconds > 0.0
    component = result.components[0]
    assert component.kind == "closed"
    assert component.status == FiberStatus.CLOSED
    assert component.reason == TerminationReason.CLOSED_LOOP
    assert component.arclength == pytest.approx(CANONICAL_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert len(component.result.poses) == 61
    assert component.seed.shape == (3, 3)
    assert np.allclose(component.seed.T @ component.seed, np.eye(3), atol=1e-10)


def test_rows_225_and_226_are_one_continuous_branch(
    row_225_discovery: ComponentDiscoveryResult, row_226_discovery: ComponentDiscoveryResult
) -> None:
    for result in (row_225_discovery, row_226_discovery):
        assert result.completeness == "complete"
        assert result.component_count == 1 and result.components[0].kind == "closed"
    upper = row_225_discovery.components[0].arclength
    lower = row_226_discovery.components[0].arclength
    assert upper == pytest.approx(ROW_225_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert lower == pytest.approx(ROW_226_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert abs(upper - lower) < 0.01 * lower


@pytest.mark.parametrize(
    "row, pool_count, raw_cluster_count, admissible_count, arclength",
    [(700, 1961, 14, 14, 5.408495), (780, 1737, 14, 14, 5.635867)],
)
def test_boundary_hugging_pixels_fold_every_candidate_into_one_closed_loop(
    row: int, pool_count: int, raw_cluster_count: int, admissible_count: int, arclength: float
) -> None:
    # Before task-continuation-gates-and-fixtures every candidate here ended
    # its discovery budget floor-locked because ``exit_snell_discriminant``
    # sits just under ``event_slowdown_margin`` along the lower half of the
    # loop.  Now the first candidate closes and the other 13 are folded by
    # SO(3) distance without a trace.
    result = discover_pixel(row, 150)
    assert result.pool_count == pool_count
    assert result.raw_cluster_count == raw_cluster_count
    assert result.admissible_count == admissible_count
    assert result.component_count == 1 and result.incomplete_count == 0
    assert result.completeness == "complete"
    assert result.events["dedup_merged"] == admissible_count - 1
    component = result.components[0]
    assert component.kind == "closed" and component.reason == TerminationReason.CLOSED_LOOP
    assert component.arclength == pytest.approx(arclength, rel=ARCLENGTH_RTOL)


def test_dark_pixel_has_no_admissible_candidate_and_is_procedurally_complete() -> None:
    """Row 40 lies inside the minimum deviation (21.84 deg): no store event is in its band."""
    result = discover_pixel(40, 150)
    assert np.degrees(np.arccos(pixel_target(40, 150) @ canonical_incident_direction())) < STORE.events.D[0] * 180 / np.pi - 0.2
    assert result.pool_count == 0
    assert result.raw_cluster_count == 0
    assert result.admissible_count == 0
    assert result.component_count == 0
    assert result.incomplete_count == 0
    assert result.completeness == "complete"
    assert result.trace_seconds == 0.0


@pytest.mark.parametrize(
    "row, column, pool_count, admissible_count, arclength",
    [(49, 0, 3225, 1, 0.189729), (50, 9, 3186, 1, 0.165418), (60, 126, 4218, 1, 0.466117)],
)
def test_caustic_edge_pixels_are_single_short_closed_loops(
    row: int, column: int, pool_count: int, admissible_count: int, arclength: float
) -> None:
    """(49, 0) and (50, 9) used to report event-terminated candidates next to
    their 0.19 / 0.17 loops: seeds on the same loop whose first 0.04 predictor
    step sent the corrector out of the trust region into a TIR region, which
    was declared an event (task-pixel-pipeline-v2 DECISION 18:22: such an
    iterate can never be accepted, so it is a rejected trial now, not an
    event).  (60, 126) is the caustic-neighbourhood pixel of the acceptance
    criteria.  All three are one closed loop (with the store's 0.2 deg band a
    single cluster; any other candidate is folded by distance)."""
    result = discover_pixel(row, column)
    assert result.pool_count == pool_count and result.admissible_count == admissible_count
    assert result.component_count == 1 and result.incomplete_count == 0
    assert result.completeness == "complete"
    assert result.events["dedup_merged"] == admissible_count - 1
    assert result.events["arc_stitched"] == 0 and result.events["arc_backward_closed_anomaly"] == 0
    component = result.components[0]
    assert component.kind == "closed"
    assert component.arclength == pytest.approx(arclength, rel=1e-4)


def test_dedup_threshold_must_be_positive() -> None:
    with pytest.raises(ValueError, match="distance_threshold"):
        discover_pixel(150, 150, distance_threshold=0.0)


# --- warm seeds ---------------------------------------------------------------------


def test_warm_seed_from_the_row_above_is_a_newton_start_not_a_separate_trace(
    canonical_discovery: ComponentDiscoveryResult,
) -> None:
    seed = canonical_discovery.components[0].seed
    cold = discover_pixel(151, 150)
    warm = discover_pixel(151, 150, extra_seeds=[seed])
    assert cold.extra_seed_count == 0 and warm.extra_seed_count == 1
    assert warm.pool_count == cold.pool_count  # the store band is unchanged
    assert cold.component_count == warm.component_count == 1
    assert cold.components[0].arclength == pytest.approx(ROW_151_ARCLENGTH, rel=ARCLENGTH_RTOL)
    # The same loop traced from another seed: its polyline length moves in the sixth digit.
    assert warm.components[0].arclength == pytest.approx(cold.components[0].arclength, rel=1e-5)
    assert warm.components[0].arclength != pytest.approx(CANONICAL_ARCLENGTH, rel=1e-4)
    # The warm seed's cluster is traced first, from the warm seed itself.
    assert distance_to_curve(warm.components[0].seed, np.asarray([seed])) < 0.05
    assert warm.events["dedup_merged"] == warm.admissible_count - 1


def test_warm_seed_far_from_every_fiber_neither_poisons_nor_adds_a_component(
    canonical_discovery: ComponentDiscoveryResult,
) -> None:
    result = discover_pixel(150, 150, extra_seeds=[np.eye(3)])
    assert result.extra_seed_count == 1
    assert result.component_count == 1 and result.incomplete_count == 0
    assert result.components[0].arclength == pytest.approx(CANONICAL_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert result.raw_cluster_count >= canonical_discovery.raw_cluster_count


# --- production budget is the only budget -----------------------------------------


def test_continuation_options_are_the_single_trace_policy() -> None:
    problem = canonical_pixel_problem(with_weights=False)
    small = ContinuationOptions(maximum_accepted_steps=50)
    truncated = trace_fiber(problem, small)
    assert truncated.status == FiberStatus.BUDGET_EXHAUSTED
    assert len(truncated.poses) == 51
    starved = discover_pixel(150, 150, continuation=small)
    assert starved.component_count == 0 and starved.incomplete_count >= 1
    assert starved.completeness == "unknown"
    assert all(c.cause == "incomplete_not_converged" for c in starved.incomplete)
    assert all(c.status == FiberStatus.BUDGET_EXHAUSTED for c in starved.incomplete)


# --- template reuse (task-strip-image-driver) ------------------------------------


def test_retarget_problem_keeps_evaluator_identity_and_rebuilds_the_chart() -> None:
    template = canonical_pixel_problem(with_weights=True)
    target = pixel_target(151, 150)
    problem = retarget_problem(template, target, np.eye(3))
    assert problem.direction_evaluator is template.direction_evaluator
    assert problem.domain_and_event_evaluator is template.domain_and_event_evaluator
    assert problem.weight_evaluators is template.weight_evaluators
    assert np.allclose(np.asarray(problem.target_chart.direction), target)
    assert np.allclose(np.asarray(problem.seed), np.eye(3))
    assert problem.target_chart.minimum_dot == template.target_chart.minimum_dot


def test_discover_components_with_a_shared_template_matches_a_fresh_problem(
    canonical_discovery: ComponentDiscoveryResult,
) -> None:
    template = canonical_pixel_problem(with_weights=False)
    shared = discover_components(
        pixel_target(150, 150), SEEDS, template=template, **DISCOVERY_KWARGS
    )
    assert shared.component_count == canonical_discovery.component_count == 1
    assert shared.pool_count == canonical_discovery.pool_count
    assert shared.admissible_count == canonical_discovery.admissible_count
    assert shared.components[0].arclength == pytest.approx(
        canonical_discovery.components[0].arclength, rel=1e-12
    )
    assert np.allclose(shared.components[0].seed, canonical_discovery.components[0].seed, atol=1e-12)


def test_template_with_a_different_scene_is_rejected() -> None:
    template = canonical_pixel_problem(with_weights=False)
    foreign = StoreSeeds(STORE, (3, 5), canonical_incident_direction())  # the sun on the other side
    with pytest.raises(ValueError, match="incident direction"):
        discover_components(pixel_target(150, 150), foreign, template=template)
    other_index = StoreSeeds(_store([(3, 5)], 1_000, refractive_index=1.33), (3, 5), canonical_sun_direction())
    with pytest.raises(ValueError, match="path"):
        discover_components(pixel_target(150, 150), other_index, template=template)


def _member_seeds(path_id: str) -> StoreSeeds:
    """``3-7``: the ``3-5`` store transported by its class element; ``3-1-2-5``: its own store."""
    from lumice_integral.path_class import build_path_class, path_class_symmetry

    faces = tuple(int(f) for f in path_id.split("-"))
    if path_id == "3-7":
        g = path_class_symmetry(build_path_class(canonical_crystal(), (3, 5)), canonical_crystal())[faces]
        return StoreSeeds(STORE, faces, canonical_sun_direction(), g)
    return StoreSeeds(_store([faces], 100_000), faces, canonical_sun_direction())


@pytest.mark.parametrize("path_id, lit", [("3-7", True), ("3-1-2-5", False)])
def test_discovery_runs_on_another_member_of_the_class(path_id: str, lit: bool) -> None:
    """Structural smoke of the generalised pipeline on ``3-7`` and ``3-1-2-5`` (numbers are pinned by
    the path-class conformance tests, not here).  ``3-1-2-5`` has no ``w > 0`` event on the canonical
    crystal, so its store and its pool are empty."""
    seeds = _member_seeds(path_id)
    assert seeds.faces == tuple(int(f) for f in path_id.split("-"))
    result = discover_components(canonical_target_direction(), seeds, **DISCOVERY_KWARGS)
    assert isinstance(result, ComponentDiscoveryResult)
    assert result.completeness in ("complete", "unknown")
    assert (result.component_count >= 1) == lit and (result.pool_count > 0) == lit
    for component in result.components:
        assert component.kind in ("closed", "arc") and component.arclength > 0.0
        assert path_domain(component.seed, seeds.faces, seeds.incident_direction, seeds.refractive_index).valid


def test_template_of_another_path_is_rejected() -> None:
    other = _member_seeds("3-7")
    template = canonical_pixel_problem(with_weights=False)  # a 3-5 problem
    with pytest.raises(ValueError, match="3-7"):
        discover_components(canonical_target_direction(), other, template=template)


# --- completeness cross-check against the store band (task phase1-seeds-from-store) --------------


def test_band_coverage_of_a_complete_pixel_has_no_suspect(canonical_discovery: ComponentDiscoveryResult) -> None:
    coverage = check_band_coverage(pixel_target(150, 150), SEEDS, canonical_discovery)
    assert coverage.event_count == canonical_discovery.pool_count == 5024
    assert coverage.near_count + coverage.corrected_count == coverage.event_count
    assert coverage.on_curve_count + coverage.inadmissible_count + coverage.suspect_count == coverage.corrected_count
    assert coverage.suspect_count == 0 and coverage.suspect_clusters == 0
    assert coverage.component_event_counts == (5024,)
    assert coverage.miss_probability_bound == pytest.approx(np.exp(-5024.0))


def test_band_coverage_reports_a_component_discovery_did_not_return() -> None:
    """Remove the (only) traced loop from the result: every band event becomes a suspect on the fiber."""
    target = pixel_target(49, 0)  # a 0.19 rad loop at the caustic, its events up to 0.117 rad off the curve as posed
    found = discover_pixel(49, 0)
    complete = check_band_coverage(target, SEEDS, found)
    assert complete.suspect_count == 0 and complete.corrected_count > 0 and complete.on_curve_count == complete.corrected_count
    missed = check_band_coverage(target, SEEDS, dataclasses.replace(found, components=()))
    assert missed.suspect_count == missed.event_count == found.pool_count and missed.suspect_clusters >= 1
    assert missed.component_event_counts == () and missed.miss_probability_bound is None
    # The suspects are fiber poses on the loop that was removed.
    assert max(distance_to_curve(seed, np.asarray(found.components[0].result.poses)) for seed in missed.suspects) < 0.08


def test_band_coverage_of_a_dark_pixel_is_empty() -> None:
    coverage = check_band_coverage(pixel_target(40, 150), SEEDS, discover_pixel(40, 150))
    assert coverage.event_count == 0 and coverage.miss_probability_bound is None


def test_miss_probability_is_the_poisson_void_probability() -> None:
    assert miss_probability(0.0, STORE_N) == 1.0
    assert miss_probability(4.0 * np.pi / STORE_N, STORE_N) == pytest.approx(np.exp(-1.0))
    assert miss_probability(4.0 * np.pi * 3.0 / STORE_N, STORE_N) == pytest.approx(np.exp(-3.0))
