"""The writing series' ch8 / ch9 signature tables recomputed with :mod:`lumice_integral.symmetry`, compared byte for byte.

The published tables were generated by the writing repository's
``08-wedge-times-fold/code/enumerate_signatures.py`` (commit ``328b879``) and
``09-pyramid/code/enumerate_signatures.py`` (``91835b3``) with
``halo_notes.math`` doing the classification.  Here the same enumeration
(:func:`lumice_integral.geometry.enumerate.enumerate_raypaths_with_stats`,
parameters as locked in each table's header: ch8 ``max_len=8``,
``entry_faces=(1, 3)``; ch9 ``max_len=6``, ``entry_faces=(1, 3, 13)``; both
``LatLonGrid(180, 360)``, PBD de-duplication, coarse-grid areas) is
classified by the migrated modules and the CSV files are rebuilt row by row
with the scripts' formats.  Every per-class number of the two chapters is in
these CSVs (ch8: the 42 signature classes with their ``Phi`` class id; ch9:
every exact ``Phi`` class and every enumerated path); the Markdown summaries
are renderings of the same cells (the ch9 one also records wall-clock
timings) and are not compared.

Only the writing repository's data files are read (``tests/_writing_repo.py``);
none of its code is imported.  About 14 minutes on an M2 Max (ch8 ~55 s per ratio,
ch9 75-130 s per tier), hence ``slow``.
"""

from __future__ import annotations

import csv
import io
import math

import numpy as np
import pytest

from _writing_repo import writing_file

from lumice_integral.geometry import HexPrism, Pyramid, fold_matrix
from lumice_integral.geometry.enumerate import RaypathRecord, enumerate_raypaths_with_stats
from lumice_integral.geometry.feasibility import LatLonGrid
from lumice_integral.symmetry import reflection_group as rg
from lumice_integral.symmetry.signature import phi_class, phi_class_table

pytestmark = pytest.mark.slow

GRID = LatLonGrid(180, 360)
SLIVER_DEG = 49.0


class Cell:
    """Aggregate of the paths of one table cell (the scripts' ``Cell``)."""

    def __init__(self) -> None:
        self.n_paths = 0
        self.area_sr = 0.0
        self.min_incidence_deg = math.inf
        self.shortest: RaypathRecord | None = None

    @property
    def sliver(self) -> bool:
        return self.min_incidence_deg > SLIVER_DEG

    def add(self, r: RaypathRecord) -> None:
        self.n_paths += 1
        self.area_sr += r.area_sr
        self.min_incidence_deg = min(self.min_incidence_deg, r.min_incidence_deg)
        if self.shortest is None or (r.length, r.faces) < (self.shortest.length, self.shortest.faces):
            self.shortest = r


def _csv_bytes(header: list[str], rows: list[list]) -> bytes:
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer)
    writer.writerow(header)
    writer.writerows(rows)
    return buffer.getvalue().encode("utf-8")


# ---- ch8: hexagonal prism, 42 signature classes per aspect ratio ----------------------------------

CH8_RATIOS = (0.2, 0.5, 1.0, 2.0, 5.0)


@pytest.mark.parametrize("ratio", CH8_RATIOS, ids=lambda r: f"ha{r:g}")
def test_ch8_signature_table_csv_is_reproduced_byte_for_byte(ratio):
    published = writing_file(f"08-wedge-times-fold/data/signature_table_{ratio:g}.csv").read_bytes()
    table = phi_class_table(HexPrism.from_ratio(CH8_RATIOS[0]))
    assert sum(r.transmittable for r in table) == 34
    by_row = {r.phi_class: r for r in table}
    crystal = HexPrism.from_ratio(ratio)
    records, _ = enumerate_raypaths_with_stats(crystal, 8, GRID, entry_faces=(1, 3), symmetry_orbit=rg.pbd_orbit)
    by_sig: dict[tuple, Cell] = {}
    for r in records:
        if r.length == 1:
            continue
        cls = phi_class(crystal, fold_matrix(crystal, r.faces), r.faces[0], r.faces[-1])
        by_sig.setdefault((by_row[cls].id, cls.signature), Cell()).add(r)
    rows = []
    for row in table:
        if not row.transmittable:
            continue
        for sig in row.signatures:
            cell = by_sig.get((row.id, sig))
            if cell is None:
                continue
            k, a, b = sig
            s = cell.shortest
            rows.append([row.id, f"{row.wedge_deg:g}", row.family, "/".join(map(str, row.folds)),
                         rg.identify(np.array(k).reshape(3, 3)).number, a, b, cell.n_paths, f"{cell.area_sr:.6f}",
                         f"{cell.min_incidence_deg:.3f}", int(cell.sliver), s.label, f"{s.area_sr:.6f}",
                         f"{s.min_incidence_deg:.3f}"])
    header = ["phi_class_id", "wedge_deg", "family", "folds", "sig_fold", "sig_entry", "sig_exit", "n_paths",
              "area_sr_sum", "min_incidence_deg", "sliver", "shortest_path", "shortest_area_sr",
              "shortest_min_incidence_deg"]
    assert _csv_bytes(header, rows) == published


# ---- ch9: pyramid, every exact Phi class and every path per geometry tier -------------------------

CH9_TIERS = ((1.0, 0.5), (0.5, 0.3), (2.0, 0.8), (1.0, 0.8), (3.0, 0.25), (0.3, 0.85))
CH9_WEDGES = (0.0, 28.0, 52.4, 56.0, 60.0, 62.0, 63.8, 80.2, 90.0)
CH9_TOL = 0.5


def _ch9_family(wedge_deg: float) -> float | None:
    return next((w for w in CH9_WEDGES if abs(wedge_deg - w) <= CH9_TOL), None)


@pytest.mark.parametrize("tier", CH9_TIERS, ids=lambda t: f"h{t[0]:g}_t{t[1]:g}")
def test_ch9_signature_and_raypath_csvs_are_reproduced_byte_for_byte(tier):
    ha, tip = tier
    label = f"h{ha:g}_t{tip:g}"
    published_classes = writing_file(f"09-pyramid/data/signature_table_{label}.csv").read_bytes()
    published_paths = writing_file(f"09-pyramid/data/raypaths_{label}.csv").read_bytes()
    pyramid = Pyramid(a=1.0, h=ha, tip_ratio=tip)
    records, _ = enumerate_raypaths_with_stats(pyramid, 6, GRID, entry_faces=(1, 3, 13), symmetry_orbit=rg.pbd_orbit)
    by_class: dict = {}
    class_of: dict = {}
    for r in records:
        if r.length == 1:
            continue
        cls = phi_class(pyramid, fold_matrix(pyramid, r.faces), r.faces[0], r.faces[-1])
        class_of[r.faces] = cls
        by_class.setdefault(cls, Cell()).add(r)

    def order(item):
        cls, cell = item
        fam = _ch9_family(cls.wedge_deg)
        return (fam is None, fam if fam is not None else cls.wedge_deg, cell.shortest.length, cell.shortest.faces)

    class_rows = []
    for cls, cell in sorted(by_class.items(), key=order):
        fam = _ch9_family(cls.wedge_deg)
        k, a, b = cls.signature
        s = cell.shortest
        class_rows.append([f"{cls.wedge_deg:.1f}", "" if fam is None else f"{fam:g}", a, b, " ".join(f"{x:g}" for x in k),
                           cell.n_paths, f"{cell.area_sr:.6f}", f"{cell.min_incidence_deg:.3f}", int(cell.sliver),
                           s.label, f"{s.area_sr:.6f}", f"{s.min_incidence_deg:.3f}"])
    class_header = ["wedge_deg", "family", "sig_entry", "sig_exit", "fold_matrix", "n_paths", "area_sr_sum",
                    "min_incidence_deg", "sliver", "shortest_path", "shortest_area_sr", "shortest_min_incidence_deg"]

    path_rows = []
    for r in sorted(records, key=lambda r: (r.length, r.faces)):
        if r.length == 1:
            path_rows.append([r.label, 1, f"{r.area_sr:.6f}", f"{r.min_incidence_deg:.3f}", "", ""])
            continue
        cls = class_of[r.faces]
        fam = _ch9_family(cls.wedge_deg)
        path_rows.append([r.label, r.length, f"{r.area_sr:.6f}", f"{r.min_incidence_deg:.3f}", f"{cls.wedge_deg:.1f}",
                          "" if fam is None else f"{fam:g}"])
    path_header = ["raypath", "length", "area_sr", "min_incidence_deg", "wedge_deg", "family"]

    assert _csv_bytes(path_header, path_rows) == published_paths
    assert _csv_bytes(class_header, class_rows) == published_classes
