"""Single-pixel component discovery: synthetic unit checks and strip-pixel regressions.

The six pixel regressions reproduce ``explore-component-discovery``
(``exp03_pixel_grid_results.csv`` and experiments #5–#7) with the same
parameters (``rng_seed=20260916``, 400k samples, 2 deg, 0.3 rad).  The
``(700,150)``/``(780,150)``/``(40,150)`` funnel counts are the survey's own
numbers; the canonical/225/226 arclengths were regenerated by this module's
implementation and recorded here as the new baseline.
"""

from __future__ import annotations

import dataclasses
import time
from types import SimpleNamespace

import jax.numpy as jnp
import numpy as np
import pytest

from lumice_integral.camera import linear_pixel_outgoing_direction
from lumice_integral.canonical_scene import (
    CANONICAL_REFRACTIVE_INDEX,
    CANONICAL_RENDER,
    canonical_crystal,
    canonical_incident_direction,
    canonical_pixel_problem,
    canonical_seed,
)
from lumice_integral.continuation import ContinuationOptions, FiberStatus, TerminationReason, trace_fiber
from lumice_integral.discovery import (
    ComponentDiscoveryResult,
    DiscoveredComponent,
    IncompleteCandidate,
    _dedup,
    _geodesic_cluster,
    detect_arclength_jump,
    discover_components,
    hot_start_component,
)
from lumice_integral.so3 import exp

RNG_SEED = 20260916
DISCOVERY_KWARGS = dict(
    rng_seed=RNG_SEED,
    prescan_samples=400_000,
    angle_tolerance_deg=2.0,
    cluster_radius_rad=0.3,
)
ARCLENGTH_RTOL = 1e-3

# Regenerated baselines (this implementation, default parameters); the survey
# recorded 4.758247 / 6.2437 / 3.1302 for the same pixels.
CANONICAL_ARCLENGTH = 4.758247
ROW_225_ARCLENGTH = 6.243734
ROW_226_ARCLENGTH = 3.130201
ROW_151_ARCLENGTH = 4.782113


def pixel_target(row: int, column: int) -> np.ndarray:
    return linear_pixel_outgoing_direction(row, column, **CANONICAL_RENDER)


def discover_pixel(row: int, column: int) -> ComponentDiscoveryResult:
    return discover_components(
        pixel_target(row, column),
        canonical_incident_direction(),
        CANONICAL_REFRACTIVE_INDEX,
        canonical_crystal(),
        **DISCOVERY_KWARGS,
    )


def _closed_record(arclength: float, poses: int) -> DiscoveredComponent:
    return DiscoveredComponent(
        seed=np.eye(3),
        result=SimpleNamespace(poses=np.zeros((poses, 3, 3))),
        arclength=arclength,
        status=FiberStatus.CLOSED,
        reason=TerminationReason.CLOSED_LOOP,
    )


def _incomplete_record(reason: TerminationReason = TerminationReason.STEP_BUDGET) -> IncompleteCandidate:
    return IncompleteCandidate(
        seed=np.eye(3),
        result=SimpleNamespace(poses=np.zeros((251, 3, 3))),
        status=FiberStatus.BUDGET_EXHAUSTED,
        reason=reason,
    )


# --- Step 1/2: types and synthetic helpers ----------------------------------


def test_result_types_are_frozen_and_count_properties_match_tuples() -> None:
    result = ComponentDiscoveryResult(
        components=(_closed_record(1.0, 10),),
        incomplete=(_incomplete_record(),),
        completeness="unknown",
        pool_count=3,
        raw_cluster_count=2,
        admissible_count=2,
    )
    assert result.component_count == 1
    assert result.incomplete_count == 1
    with pytest.raises(dataclasses.FrozenInstanceError):
        result.completeness = "complete"  # type: ignore[misc]
    with pytest.raises(dataclasses.FrozenInstanceError):
        result.components[0].arclength = 2.0  # type: ignore[misc]


def test_dedup_fingerprint_ignores_pose_counts_within_arclength_rtol() -> None:
    # row=80 failure mode: the same loop traced from three entry points with
    # 173 / 180 / 172 accepted poses is one component, not three.
    records = [
        _closed_record(3.671537, 173),
        _closed_record(3.671537 * (1 + 5e-4), 180),
        _closed_record(3.671537 * (1 - 5e-4), 172),
    ]
    result = _dedup(records, ARCLENGTH_RTOL, pool_count=333, raw_cluster_count=6)
    assert result.component_count == 1
    assert result.incomplete == ()
    assert result.completeness == "complete"
    assert result.admissible_count == 3


def test_dedup_separates_arclengths_outside_rtol() -> None:
    records = [_closed_record(6.2437, 157), _closed_record(3.1302, 80)]
    result = _dedup(records, ARCLENGTH_RTOL, pool_count=0, raw_cluster_count=2)
    assert sorted(c.arclength for c in result.components) == [3.1302, 6.2437]


def test_dedup_routes_non_closed_records_to_incomplete_and_marks_unknown() -> None:
    records = [_incomplete_record(), _incomplete_record(), _incomplete_record()]
    result = _dedup(records, ARCLENGTH_RTOL, pool_count=113, raw_cluster_count=3)
    assert result.components == ()
    assert result.incomplete_count == 3
    assert result.completeness == "unknown"


def test_dedup_of_empty_records_is_complete_with_zero_components() -> None:
    result = _dedup([], ARCLENGTH_RTOL, pool_count=210, raw_cluster_count=4)
    assert result.component_count == 0
    assert result.incomplete_count == 0
    assert result.completeness == "complete"
    assert result.admissible_count == 0


def test_geodesic_cluster_separates_two_tight_clusters() -> None:
    rng = np.random.default_rng(0)
    centres = [np.array([1.0, 0.2, -0.3]), np.array([-0.5, 1.4, 0.8])]
    rotations = []
    for centre in centres:
        for _ in range(5):
            rotations.append(np.asarray(exp(jnp.asarray(centre + 0.01 * rng.standard_normal(3)))))
    rotations = np.stack(rotations)
    clusters = _geodesic_cluster(rotations, radius=0.3)
    assert sorted(sorted(c) for c in clusters) == [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


def test_geodesic_cluster_of_empty_pool_is_empty() -> None:
    assert _geodesic_cluster(np.zeros((0, 3, 3)), radius=0.3) == []


# --- Step 3/4: pixel regressions ---------------------------------------------


@pytest.fixture(scope="module")
def canonical_discovery() -> ComponentDiscoveryResult:
    return discover_pixel(150, 150)


@pytest.fixture(scope="module")
def row_225_discovery() -> ComponentDiscoveryResult:
    return discover_pixel(225, 150)


@pytest.fixture(scope="module")
def row_226_discovery() -> ComponentDiscoveryResult:
    return discover_pixel(226, 150)


def test_canonical_pixel_has_one_closed_component(canonical_discovery: ComponentDiscoveryResult) -> None:
    result = canonical_discovery
    assert result.completeness == "complete"
    assert result.component_count == 1
    assert result.incomplete_count == 0
    component = result.components[0]
    assert component.status == FiberStatus.CLOSED
    assert component.reason == TerminationReason.CLOSED_LOOP
    assert component.arclength == pytest.approx(CANONICAL_ARCLENGTH, rel=ARCLENGTH_RTOL)
    # The discovery budget (250) was enough for the clean canonical loop.
    assert len(component.result.poses) < 250
    assert component.seed.shape == (3, 3)
    assert np.allclose(component.seed.T @ component.seed, np.eye(3), atol=1e-10)


def test_topology_boundary_rows_225_and_226_each_have_one_component_with_a_jump(
    row_225_discovery: ComponentDiscoveryResult, row_226_discovery: ComponentDiscoveryResult
) -> None:
    for result in (row_225_discovery, row_226_discovery):
        assert result.completeness == "complete"
        assert result.component_count == 1
    upper = row_225_discovery.components[0].arclength
    lower = row_226_discovery.components[0].arclength
    assert upper == pytest.approx(ROW_225_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert lower == pytest.approx(ROW_226_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert upper > 1.5 * lower
    assert detect_arclength_jump([upper, lower]) == [0]


@pytest.mark.parametrize(
    "row, pool_count, raw_cluster_count, admissible_count, incomplete_count",
    [(700, 113, 12, 12, 12), (780, 94, 13, 13, 13)],
)
def test_degenerate_pixels_report_only_budget_exhausted_incomplete_candidates(
    row: int, pool_count: int, raw_cluster_count: int, admissible_count: int, incomplete_count: int
) -> None:
    start = time.perf_counter()
    result = discover_pixel(row, 150)
    elapsed = time.perf_counter() - start
    assert result.pool_count == pool_count
    assert result.raw_cluster_count == raw_cluster_count
    assert result.admissible_count == admissible_count
    assert result.component_count == 0
    assert result.incomplete_count == incomplete_count
    assert result.completeness == "unknown"
    for candidate in result.incomplete:
        assert candidate.status == FiberStatus.BUDGET_EXHAUSTED
        assert candidate.reason == TerminationReason.STEP_BUDGET
        assert len(candidate.result.poses) == 251
    # Diagnostic only (not asserted): the survey needed 29-31 s per pixel with
    # the production budget; the discovery budget should cut that by ~10x.
    print(f"row={row} discovery elapsed {elapsed:.1f}s")


def test_dark_pixel_has_no_admissible_candidate_and_is_procedurally_complete() -> None:
    result = discover_pixel(40, 150)
    assert result.pool_count == 210
    assert result.raw_cluster_count == 4
    assert result.admissible_count == 0
    assert result.component_count == 0
    assert result.incomplete_count == 0
    assert result.completeness == "complete"


# --- Step 5: discovery budget is independent of the production budget ----------


def test_discovery_budget_and_production_budget_are_independent_options() -> None:
    problem = canonical_pixel_problem(with_weights=False)
    small = ContinuationOptions(maximum_accepted_steps=50)
    production = ContinuationOptions()
    assert small is not production
    assert production.maximum_accepted_steps == 4000
    truncated = trace_fiber(problem, small)
    assert truncated.status == FiberStatus.BUDGET_EXHAUSTED
    assert truncated.reason == TerminationReason.STEP_BUDGET
    assert len(truncated.poses) == 51
    closed = trace_fiber(problem, production)
    assert closed.status == FiberStatus.CLOSED
    assert float(closed.arclength_increments.sum()) == pytest.approx(CANONICAL_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert small.maximum_accepted_steps == 50


# --- Step 6: hot start -----------------------------------------------------------


def test_hot_start_to_the_next_row_matches_independent_discovery(
    canonical_discovery: ComponentDiscoveryResult,
) -> None:
    seed = canonical_discovery.components[0].seed
    record = hot_start_component(
        seed, pixel_target(151, 150), canonical_incident_direction(), CANONICAL_REFRACTIVE_INDEX, canonical_crystal()
    )
    assert isinstance(record, DiscoveredComponent)
    independent = discover_pixel(151, 150)
    assert independent.component_count == 1
    assert independent.components[0].arclength == pytest.approx(ROW_151_ARCLENGTH, rel=ARCLENGTH_RTOL)
    assert record.arclength == pytest.approx(independent.components[0].arclength, rel=ARCLENGTH_RTOL)
    assert record.arclength != pytest.approx(CANONICAL_ARCLENGTH, rel=1e-4)


def test_hot_start_across_the_topology_boundary_lands_on_the_new_branch(
    row_225_discovery: ComponentDiscoveryResult, row_226_discovery: ComponentDiscoveryResult
) -> None:
    seed = row_225_discovery.components[0].seed
    record = hot_start_component(
        seed, pixel_target(226, 150), canonical_incident_direction(), CANONICAL_REFRACTIVE_INDEX, canonical_crystal()
    )
    assert isinstance(record, DiscoveredComponent)
    assert record.arclength == pytest.approx(row_226_discovery.components[0].arclength, rel=ARCLENGTH_RTOL)


def test_hot_start_from_the_canonical_seed_constant_reproduces_the_canonical_component() -> None:
    record = hot_start_component(
        canonical_seed(),
        pixel_target(150, 150),
        canonical_incident_direction(),
        CANONICAL_REFRACTIVE_INDEX,
        canonical_crystal(),
    )
    assert isinstance(record, DiscoveredComponent)
    assert record.arclength == pytest.approx(CANONICAL_ARCLENGTH, rel=ARCLENGTH_RTOL)


def test_hot_start_with_a_tiny_budget_returns_an_incomplete_candidate() -> None:
    record = hot_start_component(
        canonical_seed(),
        pixel_target(150, 150),
        canonical_incident_direction(),
        CANONICAL_REFRACTIVE_INDEX,
        canonical_crystal(),
        discovery_step_budget=20,
    )
    assert isinstance(record, IncompleteCandidate)
    assert record.status == FiberStatus.BUDGET_EXHAUSTED


# --- Step 7: arclength jump detection --------------------------------------------


def test_detect_arclength_jump_flags_only_the_discontinuity() -> None:
    smooth = [5.8049, 5.8963, 6.0, 6.1, 6.2437]
    assert detect_arclength_jump(smooth) == []
    sequence = [*smooth, 3.1302, 3.2, 3.3212]
    assert detect_arclength_jump(sequence) == [4]


def test_detect_arclength_jump_edge_cases() -> None:
    assert detect_arclength_jump([]) == []
    assert detect_arclength_jump([4.7]) == []
    assert detect_arclength_jump([1.0, 1.19], relative_threshold=0.2) == []
    assert detect_arclength_jump([1.0, 1.21], relative_threshold=0.2) == [0]
    assert detect_arclength_jump([1.0, 2.0, 1.0]) == [0, 1]
    with pytest.raises(ValueError):
        detect_arclength_jump([1.0, 2.0], relative_threshold=0.0)
    with pytest.raises(ValueError):
        detect_arclength_jump([[1.0, 2.0]])
